(function(){
'use strict';
if(window.InventoryManufacturing)return;
const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
let generation=0,lastStatus=null,poll;
function css(){if(document.querySelector('link[data-manufacturing-css],link[href^="css/manufacturing.css"]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='css/manufacturing.css?v=2';link.dataset.manufacturingCss='';document.head.append(link);}
function headers(){const workspace=localStorage.getItem('inventoryos_selected_workspace_id');return workspace?{'X-Workspace-Id':workspace}:{};}
function navigation(s){const targets=document.querySelectorAll('.ios-shell-nav[aria-label="Workspace"],.sidebar-nav[aria-label="Main navigation"]');targets.forEach(nav=>{let link=nav.querySelector('[data-manufacturing-nav]');if(!link&&s.active){link=document.createElement('a');link.href='manufacturing.html';link.dataset.manufacturingNav='';link.className=nav.classList.contains('ios-shell-nav')?'ios-shell-nav-link':'sidebar-link';link.innerHTML='<span class="'+(nav.classList.contains('ios-shell-nav')?'ios-shell-nav-icon':'sidebar-icon')+'" aria-hidden="true">⚙</span> <span>Manufacturing</span>';nav.append(link);}if(link){link.hidden=!s.active;link.style.display=s.active?'':'none';if(/\/manufacturing(?:\.html)?\/?$/i.test(location.pathname)){link.classList.add('active');link.setAttribute('aria-current','page');}}});}
function settings(s){const grid=document.querySelector('.settings-grid');if(!grid)return;let card=document.getElementById('manufacturingSettingsCard');if(!card){card=document.createElement('div');card.id='manufacturingSettingsCard';card.className='card mfg-settings-card';card.setAttribute('data-location-wording-ignore','');grid.prepend(card);}const can=['owner','admin'].includes(s.role);card.innerHTML='<div class="card-title"><span class="card-icon" aria-hidden="true">⚙</span> Manufacturing mode <span class="mfg-badge">Business</span></div><p class="helper">Track measured materials, product recipes, production batches and equipment maintenance. Timers keep their deadlines while you are logged out.</p>'+(s.success?'<label style="display:flex;gap:12px;align-items:center;margin:16px 0"><input id="manufacturingModeToggle" type="checkbox" role="switch" '+(s.enabled?'checked ':'')+(!can||(!s.allowed&&!s.enabled)?'disabled':'')+'> Enable for this workspace</label><p class="helper">'+(!s.allowed?'An active Business plan is required. Saved manufacturing records are retained.':!can?'The workspace owner or an admin can switch this on.':'Off by default. This setting applies to everyone in this workspace.')+'</p>'+(s.allowed?'<a href="manufacturing.html">'+(s.enabled?'Open Manufacturing':'View saved manufacturing records')+'</a>':'<a href="billing.html?plan=business">View Business plan</a>'):'<p class="helper">Manufacturing settings could not be loaded. Refresh the page or contact support.</p>')+'<div id="manufacturingSettingResult" role="status"></div>';
 const toggle=card.querySelector('#manufacturingModeToggle');toggle?.addEventListener('change',async()=>{const was=s.enabled;toggle.disabled=true;const result=await InventoryAPI.request('/manufacturing/settings',{method:'PATCH',headers:headers(),body:JSON.stringify({enabled:toggle.checked})});if(!result.success){toggle.checked=was;document.getElementById('manufacturingSettingResult').textContent=result.error||'Could not update Manufacturing';toggle.disabled=false;return;}await refresh();});}
async function due(s){const existing=document.getElementById('manufacturingDueBanner');if(!s.active||!InventoryAPI.getSelectedInventoryHeader()||InventoryAPI.getSelectedInventoryHeader().includes(',')){existing?.remove();return;}const workspace=s.workspace_id,scope=InventoryAPI.getSelectedInventoryHeader();const r=await InventoryAPI.request('/manufacturing/timers',{headers:headers()});if(lastStatus?.workspace_id!==workspace||InventoryAPI.getSelectedInventoryHeader()!==scope)return;const timers=(r.timers||[]).filter(x=>x.display_status==='due');if(!timers.length){existing?.remove();return;}let banner=existing;if(!banner){banner=document.createElement('aside');banner.id='manufacturingDueBanner';banner.className='mfg-due-banner';banner.setAttribute('role','status');document.body.append(banner);}banner.innerHTML='<strong>'+timers.length+' manufacturing reminder'+(timers.length===1?'':'s')+' due</strong><div>'+esc(timers[0].title)+'</div><a href="manufacturing.html#timers">Review timers</a>';}
async function refresh(){if(typeof InventoryAPI==='undefined'||!InventoryAPI.isLoggedIn())return;css();const g=++generation;const s=await InventoryAPI.request('/manufacturing/status',{headers:headers()});if(g!==generation)return;lastStatus=s;navigation(s);settings(s);window.dispatchEvent(new CustomEvent('inventoryos-manufacturing-status',{detail:s}));await due(s);}
function confirmPick(plan){css();return new Promise(resolve=>{const d=document.createElement('dialog');d.className='mfg-pick-dialog';d.setAttribute('data-location-wording-ignore','');d.innerHTML='<h2>Confirm the batches you are picking</h2><p>Pick '+esc(plan.qty)+' item'+(plan.qty===1?'':'s')+' from <strong>'+esc(window.InventoryWorkspace?.formatLocationName?.(plan.location)??plan.location)+'</strong>.</p>'+(plan.picks||[]).map(x=>'<div class="mfg-pick-row"><strong>'+esc(x.batch_code)+'</strong><span>Quantity: '+esc(x.qty)+(x.expires_on?' · Expires: '+esc(x.expires_on):'')+'</span></div>').join('')+'<p>If these are not the batches you picked, cancel and check the stock first.</p><div class="mfg-actions"><button type="button" data-cancel>Cancel</button><button type="button" class="mfg-primary" data-confirm>I picked these batches</button></div>';let finished=false;const finish=value=>{if(finished)return;finished=true;d.close();d.remove();resolve(value);};d.querySelector('[data-cancel]').onclick=()=>finish(false);d.querySelector('[data-confirm]').onclick=()=>finish(true);d.addEventListener('cancel',e=>{e.preventDefault();finish(false);});document.body.append(d);d.showModal();});}
window.InventoryManufacturing={refresh,confirmPick,escapeHtml:esc};
function boot(){refresh();clearInterval(poll);poll=setInterval(()=>{if(!document.hidden)refresh();},60000);}
window.addEventListener('inventory-selection-changed',refresh);window.addEventListener('inventoryos-shell-ready',refresh);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,300),{once:true});else setTimeout(boot,300);
})();
