(function(){
'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const scope=()=>localStorage.getItem('inventoryos_selected_workspace_id')+'|'+InventoryAPI.getSelectedInventoryHeader();
let status=null,orders=[],loaded='',generation=0,currentView='needed';
const active=()=>status?.active&&status?.role!=='viewer';
async function api(path,options){const r=await InventoryAPI.request('/manufacturing'+path,options);if(!r.success)throw Error(r.error||'Could not update recipe material orders');return r;}
async function mutate(path,body={}){const identity=scope()+'|'+path+'|'+JSON.stringify(body),key='inventoryos_material_order_pending';let old;try{old=JSON.parse(localStorage.getItem(key)||'null');}catch{}const request_id=old?.identity===identity?old.request_id:crypto.randomUUID();localStorage.setItem(key,JSON.stringify({identity,request_id}));const r=await api(path,{method:'POST',body:JSON.stringify({...body,request_id})});localStorage.removeItem(key);return r;}
function names(r){return [...new Set(r.calculations.flatMap(c=>(c.recipes||[]).map(x=>x.qty+' × '+x.name)))].join(' · ');}
function supplier(r){const u=r.product_url||r.website_url;return (u?'<a href="'+esc(u)+'" target="_blank" rel="noopener">Open supplier link</a>':'Supplier link unknown')+'<br>Phone: '+esc(r.supplier_phone||'Unknown')+'<br>Email: '+esc(r.supplier_email||'Unknown');}
function card(r){const needed=r.status==='needed',awaiting=r.status==='ordered';return '<article class="mfg-card"><h3>'+esc(r.item_name)+'</h3><span class="mfg-badge">Recipe material · '+esc(r.inventory_name)+'</span><p><strong>'+esc(needed?r.quantity_display+' '+r.unit+' to order':awaiting?r.remaining_display+' '+r.unit+' still to receive':r.quantity_display+' '+r.unit+' · '+r.status)+'</strong></p><p>'+esc(names(r))+'</p><details><summary>Supplier and plan details</summary><p>'+supplier(r)+'</p><p>Planned requirement: '+esc(r.required_display+' '+r.unit)+'</p></details><div class="mfg-actions">'+(needed&&Number(r.quantity)>0?'<button data-material-action="ordered" data-id="'+r.id+'" '+(!active()?'disabled':'')+'>Mark ordered</button>':'')+(awaiting?'<button data-material-action="receive" data-id="'+r.id+'" '+(!active()?'disabled':'')+'>Receive materials</button>':'')+(['needed','ordered'].includes(r.status)&&!Number(r.received_qty)?'<button data-material-action="cancel" data-id="'+r.id+'" '+(!active()?'disabled':'')+'>'+(needed?'Remove pending material':'Cancel order')+'</button>':'')+'<a href="manufacturing.html#materials">Material & supplier details</a></div></article>';}
function render(){if(!status?.allowed){$('recipeMaterialOrders').hidden=true;return;}if(loaded!==scope())return;currentView=document.querySelector('[data-view].active')?.dataset.view||currentView;const needed=orders.filter(r=>r.status==='needed'&&Number(r.quantity)>0);const displayed=currentView==='needed'?needed:currentView==='ordered'?orders.filter(r=>r.status==='ordered'):currentView==='received'?[]:orders;
 const mount=$('recipeMaterialOrders');mount.hidden=false;mount.innerHTML='<div class="mfg-toolbar"><div><h2>Recipe materials</h2><p class="mfg-muted">Shared ingredients from your saved calculations are consolidated here. Quantities use each material’s unit.</p></div><a href="manufacturing.html#calculate">Calculate recipe materials</a></div>'+(!status.enabled?'<div class="mfg-notice">Manufacturing mode is off. Enable it in Settings to place or receive material orders.</div>':'')+(currentView==='received'?'<div class="mfg-notice">Recipe materials are received directly into their material batch and storage area. They appear in Manufacturing → Materials, rather than whole-product destination assigning.</div>':'<div class="mfg-grid">'+(displayed.length?displayed.map(card).join(''):'<div class="mfg-empty">'+(currentView==='needed'?'No recipe materials need ordering. Calculate recipes to build a combined plan.':currentView==='ordered'?'No material orders are awaiting receipt.':'No recipe material plans have been saved yet.')+'</div>')+'</div>')+(currentView==='all'&&orders.some(r=>r.status==='needed')?'<div class="mfg-actions"><button data-material-action="clear" '+(!active()?'disabled':'')+'>Clear all pending recipe material plans</button></div>':'')+'<p class="mfg-muted">Recipe emails are one daily combined summary, at 5pm UK time by default. Change the time in Email reminders. The optional email add-on must be active and reminders enabled. Material orders do not create finished products or deduct stock.</p>';
 ['needed','ordered'].forEach(view=>{const el=$(view+'Count');if(!el)return;const productCount=Number(el.dataset.productCount??(el.textContent.match(/\d+/)?.[0]||0));el.dataset.productCount=productCount;const extra=view==='needed'?needed.length:orders.filter(r=>r.status==='ordered').length;el.textContent=' ('+(productCount+extra)+')';});if(needed.length){$('summary').classList.remove('good');$('summary').textContent='Recipe materials: '+needed.length+' combined material'+(needed.length===1?'':'s')+' need reordering. Product reorder cards are listed separately below.';}
}
async function load(){const g=++generation,s=scope();try{status=await api('/status');if(g!==generation)return;if(!status.allowed){$('recipeMaterialOrders').hidden=true;return;}const r=await api('/material-orders');if(g!==generation||s!==scope())return;orders=r.requests||[];loaded=s;render();}catch(error){if(g!==generation)return;$('recipeMaterialOrders').hidden=false;$('recipeMaterialOrders').innerHTML='<div class="mfg-notice">'+esc(error.message)+'</div>';}}
function receive(r){const started=scope(),dialog=$('recipeMaterialDialog');$('recipeMaterialDialogTitle').textContent='Receive '+r.item_name;$('recipeMaterialDialogBody').innerHTML='<form class="mfg-form"><p>Still to receive: '+esc(r.remaining_display+' '+r.unit)+'</p><label>Quantity received ('+esc(r.unit)+')<input type="number" name="qty" required min="'+(r.unit==='each'?'1':'0.000001')+'" step="'+(r.unit==='each'?'1':'0.000001')+'" max="'+esc(r.remaining_display)+'" value="'+esc(r.remaining_display)+'"></label><label>Supplier batch number<input name="batch_code" required maxlength="80" value="'+esc('ORDER-'+r.id.slice(0,8)+'-'+Date.now().toString(36))+'"></label><label>Storage area<input name="location" required value="Holding"></label><label>Expiry date (optional)<input name="expires_on" type="date"></label><p class="mfg-muted">Only the amount received is added to this material batch. The rest stays on order. Finished-product stock is unchanged.</p><div class="mfg-error" role="alert"></div><div class="mfg-actions"><button type="submit" class="mfg-primary">Confirm materials received</button><button type="button" data-material-close>Cancel</button></div></form>';dialog.showModal();const form=$('recipeMaterialDialogBody').querySelector('form');form.querySelector('[data-material-close]').onclick=()=>dialog.close();form.onsubmit=async e=>{e.preventDefault();const b=form.querySelector('[type=submit]');b.disabled=true;try{if(started!==scope())throw Error('Inventory changed. Close this form and start again.');await mutate('/material-orders/'+r.id+'/receive',Object.fromEntries(new FormData(form)));dialog.close();await load();}catch(error){form.querySelector('.mfg-error').textContent=error.message;b.disabled=false;}};}
document.addEventListener('click',async e=>{if(e.target.closest('#refreshBtn'))load();const b=e.target.closest('[data-material-action]');if(!b||b.disabled)return;const action=b.dataset.materialAction,r=orders.find(o=>o.id===b.dataset.id);if(action==='receive')return receive(r);const confirm=action==='clear'?'Clear every pending recipe material plan in this inventory? Placed orders and stock stay in place.':action==='cancel'?'Remove this material plan/order? Its recipe requirement will be removed from the pending list. Stock stays in place.':'Confirm you have placed the order for '+r.quantity_display+' '+r.unit+' of '+r.item_name+'?';if(!window.confirm(confirm))return;b.disabled=true;try{await mutate('/material-orders/'+(action==='clear'?'clear':r.id+'/'+action),action==='ordered'?{expected_quantity:r.quantity}:{});await load();}catch(error){$('status').textContent=error.message;b.disabled=false;}});
document.addEventListener('inventoryos-reorders-rendered',()=>{['needed','ordered'].forEach(v=>{const el=$(v+'Count');if(el)el.dataset.productCount=el.textContent.match(/\d+/)?.[0]||'0';});if(loaded===scope())render();});
window.addEventListener('inventory-selection-changed',()=>{$('recipeMaterialDialog').close();loaded='';orders=[];load();});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load();
})();
