(function(){
'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sections=['Overview','Materials','Recipes','Production','Batches','Equipment','Timers'];
let data={},products=[],boxes=[],selected=location.hash.slice(1)||'overview',clockOffset=0,generation=0,interval,loadedScope='',loading=false,batchSearch=null;
const scope=()=>localStorage.getItem('inventoryos_selected_workspace_id')+'|'+InventoryAPI.getSelectedInventoryHeader();
const canWrite=()=>data.status?.allowed&&data.status.role!=='viewer';const active=()=>canWrite()&&data.status?.enabled;
const btn=(label,action,record='',manage=false)=>`<button type="button" data-action="${esc(action)}" data-id="${esc(record)}" ${!(action.startsWith('status-')?canWrite()&&['owner','admin'].includes(data.status.role):manage?canWrite():active())?'disabled':''}>${esc(label)}</button>`;
const badge=(label,kind='')=>`<span class="mfg-badge ${kind}">${esc(label)}</span>`;
const empty=message=>`<div class="mfg-empty">${esc(message)}</div>`;
const card=(title,body,actions='')=>`<article class="mfg-card"><h3>${esc(title)}</h3>${body}${actions?'<div class="mfg-actions">'+actions+'</div>':''}</article>`;
const opts=(rows,field,value='',blank='Choose…')=>`<option value="">${esc(blank)}</option>`+rows.map(x=>`<option value="${esc(x.id)}" ${String(x.id)===String(value)?'selected':''}>${esc(x[field])}</option>`).join('');
const input=(label,name,value='',type='text',extra='')=>`<label>${esc(label)}<input name="${esc(name)}" value="${esc(value??'')}" type="${type}" ${extra}></label>`;
const select=(label,name,options)=>`<label>${esc(label)}<select name="${esc(name)}">${options}</select></label>`;
const options=(values,value)=>values.map(x=>`<option value="${esc(x[0])}" ${x[0]===value?'selected':''}>${esc(x[1])}</option>`).join('');
function display(q,unit){const f={each:1,g:1,kg:1000,ml:1,l:1000,mm:1,cm:10,m:1000}[unit]||1;return (Number(q)/f).toFixed(6).replace(/\.?0+$/,'')||'0';}
function loc(v){return window.InventoryWorkspace?.formatLocationName?.(v)??String(v??'');}
function datetime(v){return new Date(v).toLocaleString('en-GB');}
function expired(v){return v&&String(v).slice(0,10)<new Date().toISOString().slice(0,10);}
async function api(path,options){const r=await InventoryAPI.request('/manufacturing'+path,options);if(!r.success)throw Error(r.error||'Could not complete this request');return r;}
async function mutate(path,body,method='POST'){
 const identity=scope()+'|'+InventoryAPI.getUser()?.id+'|'+method+'|'+path+'|'+JSON.stringify(body),key='inventoryos_mfg_pending_v1';let pending;try{pending=JSON.parse(localStorage.getItem(key)||'null');}catch{}
 const request_id=pending?.identity===identity?pending.request_id:crypto.randomUUID();localStorage.setItem(key,JSON.stringify({identity,request_id}));
 const r=await api(path,{method,body:JSON.stringify({...body,request_id})});if(JSON.parse(localStorage.getItem(key)||'null')?.request_id===request_id)localStorage.removeItem(key);return r;
}
function notice(message,error=false){$('mfgStatus').hidden=!message;$('mfgStatus').textContent=message;$('mfgStatus').className='mfg-notice'+(error?' error':'');}
async function load(){const g=++generation,s=scope();loading=true;try{const status=await api('/status');if(g!==generation)return;data.status=status;clockOffset=new Date(status.server_now).getTime()-Date.now();if(!status.allowed){$('mfgWorkspace').hidden=true;notice('Manufacturing is included in Business. Upgrade in Settings → Billing to use these tools.');const a=document.createElement('a');a.href='billing.html?plan=business';a.textContent=' View Business plan';$('mfgStatus').append(a);return;}
 const [o,p,b]=await Promise.allSettled([api('/overview'),InventoryAPI.request('/products'),InventoryAPI.request('/boxes')]);if(g!==generation||s!==scope())return;if(o.status!=='fulfilled')throw o.reason;data=o.value;if(batchSearch?.query){const found=await api('/batches/search?query='+encodeURIComponent(batchSearch.query));if(g!==generation||s!==scope())return;batchSearch={query:batchSearch.query,...found};}products=p.status==='fulfilled'&&p.value.success?p.value.products:[];boxes=b.status==='fulfilled'&&b.value.success?b.value.boxes:[];loadedScope=s;clockOffset=new Date(data.status.server_now).getTime()-Date.now();$('mfgWorkspace').hidden=false;notice(!data.status.enabled?'Manufacturing mode is off. Saved records are still available. Enable it in Settings before receiving materials or completing production.':data.status.role==='viewer'?'You have view-only access to this workspace.':'');render();}catch(e){if(g!==generation)return;$('mfgWorkspace').hidden=true;notice(e.message,true);}finally{if(g===generation)loading=false;}}
function toolbar(title,description,actions){return `<div class="mfg-toolbar"><div><h2>${esc(title)}</h2><p class="mfg-muted">${esc(description)}</p></div><div class="mfg-actions">${actions||''}</div></div>`;}
function render(){if(!sections.some(x=>x.toLowerCase()===selected))selected='overview';$('mfgTabs').innerHTML=sections.map(s=>`<button type="button" role="tab" aria-selected="${selected===s.toLowerCase()}" data-tab="${s.toLowerCase()}">${s}</button>`).join('');const views={overview,materials,recipes,production,batches,equipment,timers};$('mfgView').innerHTML=views[selected]();countdowns();}
function overview(){const due=(data.timers||[]).filter(t=>t.display_status==='due').length,maintenance=(data.equipment||[]).filter(e=>!e.archived&&(e.clean_due||e.replace_due)).length;return toolbar('From materials to finished stock','Choose one inventory at the top. Everything here belongs to that inventory.',btn('Start a timer','timer'))+`<div class="mfg-grid">${card('Materials',`<div class="mfg-stat">${data.materials.filter(m=>!m.archived).length}</div><p>Raw ingredients and packaging, measured in each, grams, litres or metres.</p>`, '<button data-tab="materials">Open materials</button>')}${card('Production',`<div class="mfg-stat">${data.runs.length}</div><p>Completed batches. Components are deducted and finished items added together.</p>`,'<button data-tab="production">Open production</button>')}${card('Maintenance & timers',`<div class="mfg-stat">${due+maintenance}</div><p>${due} timer(s) due · ${maintenance} tool(s) needing attention.</p>`,'<button data-tab="equipment">Equipment</button><button data-tab="timers">Timers</button>')}</div><div class="mfg-notice"><strong>Getting started</strong><ol><li>Add your materials and receive their batches.</li><li>Create a finished product and a recipe, using quantities per finished item.</li><li>Preview a production run to see the exact material batches to use.</li><li>When the products are finished, confirm production. They become ordinary stock you can find, move, label and dispatch.</li></ol><p>Use a timer while products cure or a cleaning deadline approaches. Timers never automatically change stock or mark equipment cleaned.</p></div>`;}
function materials(){return toolbar('Materials & packaging','Material quantities are separate from whole-item saleable stock.',btn('Add material','material')+btn('Receive a batch','receive'))+`<div class="mfg-grid">${data.materials.map(m=>{const lots=data.rawlots.filter(l=>l.material_id===m.id);const eligible=Number(m.eligible_display_qty||0);return card(m.name,badge(m.archived?'Archived':m.kind==='packaging'?'Packaging':'Raw material')+`<p><strong>${esc(Number(eligible.toFixed(6)).toLocaleString('en-GB',{maximumFractionDigits:6}))} ${esc(m.unit)}</strong> eligible for production</p><p>${m.batch_count??lots.length} batch(es) recorded</p>`,btn('Receive','receive',m.id)+(canWrite()?btn(m.archived?'Restore':'Archive','archive-material',m.id):''));}).join('')||empty('Add your first raw material or packaging item.')}</div>`;}
function recipes(){return toolbar('Product recipes','A bill of materials: how much of each component makes one finished item.',btn('Create recipe','recipe')+btn('New finished product','product'))+`<div class="mfg-grid">${data.recipes.map(r=>card(r.name,badge(r.archived?'Archived':'Version '+r.version)+`<p>${esc(products.find(p=>String(p.id)===r.product_id)?.description||'Saved finished product')}</p><ul>${r.components.map(c=>`<li>${esc(c.name)} · ${esc(display(c.qty,c.unit))} ${esc(c.unit)} per item</li>`).join('')}</ul><p>${r.equipment.length} linked tool(s)</p>`,btn('Edit recipe','recipe',r.id)+btn(r.archived?'Restore':'Archive','archive-recipe',r.id))).join('')||empty('Create a recipe after receiving your first materials.')}</div>`;}
function production(){return toolbar('Production','Preview the material picks. Complete only when the finished products are ready.',btn('New production run','produce')+btn('Start a ready timer','timer-ready'))+`<div class="mfg-notice">Production uses eligible material batches with the earliest expiry first. The preview shows their batch numbers, locations and quantities. If stock changes, you must preview again.</div><div class="mfg-grid">${data.runs.map(r=>card(r.product_name,badge(r.batch_code)+`<p><strong>${r.qty} finished items</strong> → ${esc(loc(r.destination))}</p><p>Barcode ${esc(r.barcode)}<br>Completed ${esc(datetime(r.created_at))}${r.expires_on?'<br>Expires '+esc(String(r.expires_on).slice(0,10)):''}</p>`, '<a href="barcodeprinting.html">Print barcode labels</a>')).join('')||empty('Your completed production batches will appear here.')}</div>`;}
function batches(){
 const raws=(batchSearch?.rawlots||data.rawlots).map(l=>({...l,type:'material',title:l.name,quantity:l.display_qty+' '+l.unit}));
 const finished=(batchSearch?.finished||data.finished).map(l=>({...l,type:'finished',title:l.product_name,quantity:l.qty+' finished items'}));
 return toolbar('Batches & traceability','Latest batches are shown here. Search by batch number or product to find older records.','')+
 `<div class="mfg-search"><input id="mfgBatchQuery" aria-label="Search by batch number or product" value="${esc(batchSearch?.query||'')}" placeholder="Batch number or product name" maxlength="160"><button type="button" data-action="batch-search">Search</button><button type="button" data-action="batch-clear">Show latest</button></div>`+
 `<div class="mfg-grid">${[...raws,...finished].map(l=>card(l.title,badge(l.batch_code)+badge(expired(l.expires_on)?'Expired':l.status,l.status==='recalled'||expired(l.expires_on)?'danger':l.status==='held'?'warning':'')+`<p><strong>${esc(l.quantity)}</strong>${l.untracked?'<br>Origin unknown; no production history recorded.':''}<br>${esc(l.location?loc(l.location):l.locations.map(x=>loc(x.location)+': '+x.qty).join(' · ')||'No remaining stock')}${l.expires_on?'<br>Expires '+esc(String(l.expires_on).slice(0,10)):''}</p>`,`<button data-action="trace-${l.type}" data-id="${l.id}">Trace batch</button>`+btn('Change status','status-'+l.type,l.id,true)+(l.type==='material'?btn('Adjust / relocate','adjust',l.id):''))).join('')||empty('No matching batches. Receive materials or complete production to add one.')}</div>`;
}
function equipment(){return toolbar('Equipment & maintenance','Track real operating hours or uses. Cleaning and replacement keep an audit history.',btn('Add equipment','equipment'))+`<div class="mfg-grid">${data.equipment.map(e=>card(e.name,badge(e.archived?'Archived':e.replace_due?'Replacement due':e.clean_due?'Cleaning due':'Ready',e.replace_due?'danger':e.clean_due?'warning':'')+`<p>${esc(e.total_uses)} total uses · ${esc(e.total_hours)} operating hours</p><p>Replacement: ${e.remaining_life===null?'Not set':esc(e.remaining_life)+' '+e.lifespan_metric+' remaining'}<br>Cleaning: ${e.remaining_service===null?'Not set':esc(e.remaining_service)+' '+e.maintenance_metric+' remaining'}</p>`,btn('Log actual usage','equipment-log',e.id)+btn('Cleaned','equipment-clean',e.id)+btn('Replaced','equipment-replace',e.id)+btn('Edit rules','equipment',e.id)+`<button data-action="equipment-history" data-id="${e.id}">History</button>`+btn(e.archived?'Restore':'Archive','archive-equipment',e.id))).join('')||empty('Add a tool with a use limit or cleaning interval, then link it to a recipe.')}</div><p class="mfg-muted">Recipe usage is recorded when production is completed. Avoid logging it twice. Timer duration is elapsed time; it does not add operating hours.</p>`;}
function timers(){return toolbar('Persistent timers','Deadlines stay saved while you log out. Choose optional email reminders when you start a timer.',btn('Start timer','timer'))+`<div class="mfg-grid">${data.timers.map(t=>card(t.title,badge(t.display_status,t.display_status==='due'?'warning':'')+`<div class="mfg-countdown" data-countdown="${esc(t.due_at)}" data-status="${t.status}"></div><p>${esc(datetime(t.due_at))}<br>${t.kind==='clean'?'Cleaning reminder':t.kind==='ready'?'Product ready reminder':'General reminder'}</p><p>${t.notify_email?(t.email_sent_at?'Email sent':t.email_error||'Email reminder enabled for the account that created this timer'):'In-app reminder only'}</p>`,['running','due'].includes(t.status)?btn('Acknowledge','timer-acknowledged',t.id,true)+btn('Cancel timer','timer-cancelled',t.id,true):'')).join('')||empty('Start a timer such as “Clean press in 10 hours” or “Candles ready in 10 hours”.')}</div>`;}
function countdowns(){document.querySelectorAll('[data-countdown]').forEach(el=>{if(!['running','due'].includes(el.dataset.status)){el.textContent='Completed';return;}let seconds=Math.max(0,Math.ceil((new Date(el.dataset.countdown).getTime()-Date.now()-clockOffset)/1000));if(!seconds){el.textContent='Due now';return;}const days=Math.floor(seconds/86400);seconds%=86400;const hours=Math.floor(seconds/3600),mins=Math.floor(seconds%3600/60),secs=seconds%60;el.textContent=(days?days+'d ':'')+String(hours).padStart(2,'0')+':'+String(mins).padStart(2,'0')+':'+String(secs).padStart(2,'0');});}
function dialog(title,html){$('mfgDialogTitle').textContent=title;$('mfgDialogBody').innerHTML=html;$('mfgDialog').showModal();}
function form(title,fields,fn,label='Save'){
 const started=scope();dialog(title,`<form class="mfg-form">${fields}<div class="mfg-error" role="alert"></div><div class="mfg-actions"><button type="submit" class="mfg-primary">${esc(label)}</button><button type="button" data-close>Cancel</button></div></form>`);
 const f=$('mfgDialogBody').querySelector('form');f.querySelector('[data-close]').onclick=()=> $('mfgDialog').close();f.addEventListener('submit',async e=>{e.preventDefault();if(started!==scope()){f.querySelector('.mfg-error').textContent='Workspace selection changed. Close this form and start again.';return;}const submit=f.querySelector('[type=submit]');submit.disabled=true;f.querySelector('.mfg-error').textContent='';try{const values=Object.fromEntries(new FormData(f));const result=await fn(values,f);if(result?.keep_open)return;$('mfgDialog').close();await load();window.InventoryManufacturing?.refresh();}catch(error){f.querySelector('.mfg-error').textContent=error.message;submit.disabled=false;}});return f;
}
function materialForm(){form('Add material',input('Material name','name','','text','required maxlength="160"')+select('Type','kind',options([['raw','Raw material'],['packaging','Packaging']],'raw'))+select('Quantity unit','unit',options([['each','Each'],['g','Grams (g)'],['kg','Kilograms (kg)'],['l','Litres (l)'],['ml','Millilitres (ml)'],['m','Metres (m)'],['cm','Centimetres (cm)'],['mm','Millimetres (mm)']],'g'))+'<p class="mfg-muted">Keep this unit consistent. Recipes can convert within the same measurement type.</p>',v=>mutate('/materials',v));}
function receiveForm(record){const f=form('Receive a material batch',select('Material','material_id',opts(data.materials.filter(m=>!m.archived),'name',record))+input('Batch number','batch_code','','text','required maxlength="80"')+input('Quantity in the material’s unit','qty','','number','required min="0.000001" step="0.000001"')+input('Location / storage area','location','','text','required')+input('Expiry date (optional)','expires_on','','date'),v=>mutate('/materials/receive',v),'Receive batch');f.querySelector('[name=material_id]').required=true;}
function productForm(){form('New finished product',input('Product name','name','','text','required')+input('Barcode (optional; generated if left blank)','barcode')+'<p class="mfg-muted">This creates the item in normal inventory without adding stock. Production adds its finished quantity later.</p>',v=>mutate('/products',v));}
function componentRow(component={}){return `<div class="mfg-component" data-component><div class="mfg-pair">${select('Material','material',opts(data.materials.filter(m=>!m.archived||m.id===component.material_id),'name',component.material_id))}${input('Quantity per finished item','quantity',component.qty?display(component.qty,component.unit):'','','required')}</div><div class="mfg-pair">${select('Unit','unit',options((data.units||[]).map(u=>[u,u]),component.unit||'g'))}<button type="button" data-remove-row>Remove material</button></div></div>`;}
function toolRow(tool={}){return `<div class="mfg-component" data-tool>${select('Equipment','tool',opts(data.equipment.filter(e=>!e.archived||e.id===tool.equipment_id),'name',tool.equipment_id))}${select('Usage basis','basis',options([['per_run','Per production batch'],['per_item','Per finished item']],tool.basis||'per_run'))}<div class="mfg-pair">${input('Uses','uses',tool.uses||'0','number','min="0" step="0.000001"')}${input('Operating hours','hours',tool.hours||'0','number','min="0" step="0.000001"')}</div><button type="button" data-remove-row>Remove tool</button></div>`;}
function recipeForm(record){const r=data.recipes.find(x=>x.id===record);const f=form(r?'Edit recipe':'Create recipe',input('Recipe name','name',r?.name||'','text','required')+select('Finished product','product_id',opts(products.map(p=>({...p,label:p.description+' · '+p.barcode})),'label',r?.product_id))+'<p class="mfg-muted">Choose an existing product or create one using New finished product in Recipes.</p><div id="mfgComponents">'+(r?.components||[{}]).map(componentRow).join('')+'</div><button type="button" id="mfgAddComponent">Add material</button><div id="mfgTools">'+(r?.equipment||[]).map(toolRow).join('')+'</div><button type="button" id="mfgAddTool">Link equipment</button>',(v,f)=>{const components=[...f.querySelectorAll('[data-component]')].map(row=>({material_id:row.querySelector('[name=material]').value,qty:row.querySelector('[name=quantity]').value,unit:row.querySelector('[name=unit]').value})),equipment=[...f.querySelectorAll('[data-tool]')].map(row=>({equipment_id:row.querySelector('[name=tool]').value,basis:row.querySelector('[name=basis]').value,uses:row.querySelector('[name=uses]').value,hours:row.querySelector('[name=hours]').value}));return mutate('/recipes'+(record?'/'+record:''),{name:v.name,product_id:v.product_id,components,equipment},record?'PATCH':'POST');});f.querySelector('[name=product_id]').required=true;f.querySelector('#mfgAddComponent').onclick=()=>f.querySelector('#mfgComponents').insertAdjacentHTML('beforeend',componentRow());f.querySelector('#mfgAddTool').onclick=()=>f.querySelector('#mfgTools').insertAdjacentHTML('beforeend',toolRow());f.addEventListener('click',e=>{if(e.target.closest('[data-remove-row]'))e.target.closest('.mfg-component').remove();});}
function equipmentForm(record){const e=data.equipment.find(x=>x.id===record)||{};form(record?'Edit equipment rules':'Add equipment',input('Equipment name','name',e.name,'text','required')+'<div class="mfg-pair">'+select('Lifespan measured in','lifespan_metric',options([['uses','Uses'],['hours','Operating hours']],e.lifespan_metric||'uses'))+input('Replace after (optional)','lifespan_limit',e.lifespan_limit,'number','min="0.000001" step="0.000001"')+'</div><div class="mfg-pair">'+select('Cleaning measured in','maintenance_metric',options([['uses','Uses'],['hours','Operating hours']],e.maintenance_metric||'uses'))+input('Clean every (optional)','maintenance_every',e.maintenance_every,'number','min="0.000001" step="0.000001"')+'</div><p class="mfg-muted">For example: replace after 30 uses and clean every 10 operating hours. Actual hours come from production usage or a manual log.</p>',v=>mutate('/equipment'+(record?'/'+record:''),v,record?'PATCH':'POST'));}
function equipmentAction(action,record){const e=data.equipment.find(x=>x.id===record);form((action==='log'?'Log usage for ':action==='clean'?'Confirm cleaned: ':'Confirm replaced: ')+e.name,(action==='log'?'<div class="mfg-pair">'+input('Additional uses','uses','0','number','min="0" step="0.000001"')+input('Additional operating hours','hours','0','number','min="0" step="0.000001"')+'</div>':'<p class="mfg-muted">'+(action==='clean'?'Cleaning starts the maintenance interval again. The lifespan counter continues.':'Replacement starts a new lifespan and maintenance interval. Previous usage stays in history.')+'</p>')+input('Note (optional)','note'),v=>mutate('/equipment/'+record+'/action',{...v,action}),'Confirm');}
function timerForm(kind='other'){form('Start persistent timer',input('Timer name','title',kind==='ready'?'Product ready':'','text','required maxlength="160"')+select('Reminder type','kind',options([['other','General reminder'],['clean','Cleaning'],['ready','Product ready']],kind))+'<div class="mfg-pair">'+input('Ready in','duration','10','number','required min="0.016667" max="8760" step="0.000001"')+select('Time unit','duration_unit',options([['minutes','Minutes'],['hours','Hours'],['days','Days']],'hours'))+'</div>'+select('Linked equipment (optional)','equipment_id',opts(data.equipment.filter(e=>!e.archived),'name','','None'))+`<label><input name="notify_email" type="checkbox" ${data.status.email_ready?'':'disabled'}> Email my account when this is due</label><p class="mfg-muted">${data.status.email_ready?'Email goes to your verified account address.':'Email reminders are currently unavailable.'} The deadline continues while you are logged out. Reminders resume after a temporary service outage. This does not automatically change stock or mark equipment cleaned.</p>`,v=>{const factor={minutes:60,hours:3600,days:86400}[v.duration_unit];return mutate('/timers',{title:v.title,kind:v.kind,equipment_id:v.equipment_id||null,duration_seconds:Math.round(Number(v.duration)*factor),notify_email:v.notify_email==='on'});},'Start timer');}
function adjustForm(record){const l=[...(batchSearch?.rawlots||[]),...data.rawlots].find(x=>x.id===record);form('Adjust material batch '+l.batch_code,input('Actual remaining quantity ('+l.unit+')','qty',l.display_qty,'number','required min="0" step="0.000001"')+input('Location','location',l.location,'text','required')+input('Reason','reason','','text','required')+'<p class="mfg-muted">This is an audited stock adjustment. It does not alter earlier production runs.</p>',v=>mutate('/material-lots/'+record,v,'PATCH'));}
function statusForm(type,record){const l=(type==='material'?[...(batchSearch?.rawlots||[]),...data.rawlots]:[...(batchSearch?.finished||[]),...data.finished]).find(x=>x.id===record);form('Change batch status: '+l.batch_code,select('Status','status',options([['available','Available'],['held','Held — blocked for use'],['recalled','Recalled — blocked for use']],l.status))+input('Reason','reason','','text','required')+'<p class="mfg-muted">Holding or recalling a material also blocks finished batches made with it. Releasing a source material does not automatically release its finished products. Only the owner or a workspace admin can change batch status.</p>',v=>mutate('/batches/'+record+'/status',{...v,type},'PATCH'));}
function eventDetails(d){const parts=[];if(d.reason)parts.push(d.reason);if(d.note)parts.push(d.note);if(d.name)parts.push(d.name);if(d.status)parts.push('Status: '+d.status);if(d.qty!==undefined)parts.push('Quantity: '+d.qty+(d.unit?' '+d.unit:''));if(d.uses!==undefined)parts.push('Uses: '+d.uses);if(d.hours!==undefined)parts.push('Hours: '+d.hours);if(d.enabled!==undefined)parts.push(d.enabled?'Enabled':'Disabled');if(d.archived!==undefined)parts.push(d.archived?'Archived':'Restored');if(d.duration_seconds)parts.push('Duration: '+d.duration_seconds/3600+' hours');if(d.batch_code)parts.push('Batch: '+d.batch_code);return parts.join(' · ')||'Recorded in workspace history';}
function table(headers,rows){return '<div class="mfg-table-wrap"><table class="mfg-table"><thead><tr>'+headers.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(cell=>'<td>'+esc(cell??'')+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';}
async function trace(type,record){dialog('Batch trace','<p>Loading batch history…</p>');try{const t=await api('/trace/'+type+'/'+record);$('mfgDialogBody').innerHTML='<h3>'+esc(t.lot.batch_code)+'</h3><p class="mfg-muted">'+esc(t.lot.status)+(t.lot.untracked?' · Original source not recorded':'')+'</p><h3>Materials consumed</h3>'+table(['Material','Source batch','Location','Quantity'],t.sources.map(x=>[x.name,x.batch_code,loc(x.location),display(x.consumed_qty,x.unit)+' '+x.unit]))+'<h3>Production</h3>'+table(['Finished product','Batch','Made','Destination'],t.runs.map(x=>[x.product_name,x.batch_code,x.qty,loc(x.destination)]))+'<h3>Finished-stock history</h3>'+table(['When','Action','Location','Quantity','Packing job'],t.ledger.map(x=>[datetime(x.created_at),x.context.action,loc(x.location),x.qty,x.context.packing_job_id||'']))+'<h3>Audit history</h3>'+table(['When','Action','Details'],t.events.map(x=>[datetime(x.created_at),x.kind,eventDetails(x.data)]));}catch(e){$('mfgDialogBody').textContent=e.message;}}
async function history(record){dialog('Equipment history','<p>Loading…</p>');try{const r=await api('/equipment/'+record+'/history');$('mfgDialogBody').innerHTML=table(['When','Action','Details'],r.events.map(e=>[datetime(e.created_at),e.kind,eventDetails(e.data)]));}catch(e){$('mfgDialogBody').textContent=e.message;}}
function produceForm(){const f=form('Preview production',select('Recipe','recipe_id',opts(data.recipes.filter(r=>!r.archived),'name'))+input('Finished quantity','qty','1','number','required min="1" max="1000000" step="1"')+input('Finished batch number','batch_code','','text','required maxlength="80"')+input('Finished expiry date (optional)','expires_on','','date')+select('Destination location','box_id',opts(boxes.map(b=>({...b,label:loc(b.box_name)})),'label'))+'<p class="mfg-muted">Create missing locations in the Locations page first. Preview does not change stock.</p>',async v=>{const previewScope=scope();const r=await api('/production/preview',{method:'POST',body:JSON.stringify(v)});if(previewScope!==scope())throw Error('Workspace selection changed. Preview again.');productionPlan(v,r.plan);return {keep_open:true};},'Preview material picks');f.querySelector('[name=recipe_id]').required=true;f.querySelector('[name=box_id]').required=true;}
function productionPlan(body,p){const started=scope();dialog('Production plan: '+p.recipe_name,`<div class="mfg-notice"><strong>${p.qty} ${esc(p.product_name)}</strong> → ${esc(loc(p.destination))}<br>Finished batch ${esc(p.batch_code)}</div>`+p.components.map(c=>card(c.name,`<p>Need ${esc(c.display_required)} ${esc(c.unit)}</p>`+table(['Material batch','Pick from','Quantity'],c.allocations.map(a=>[a.batch_code,loc(a.location),a.display_qty+' '+c.unit]))+(Number(c.shortage)>0?'<p class="mfg-error">Not enough eligible stock for this component.</p>':''))).join('')+(p.tools.length?'<h3>Equipment usage</h3>'+table(['Tool','Uses','Hours','After production'],p.tools.map(e=>[e.name,e.uses,e.hours,e.replace_due?'Replacement due':e.clean_due?'Cleaning due':'Within limits'])):'')+`<p class="mfg-muted">Confirm only when these batches were used and the finished products are ready. The entire operation commits together. Use a timer first if the products still need time.</p><div class="mfg-error" role="alert"></div><div class="mfg-actions"><button type="button" data-plan-close>Back</button><button type="button" data-plan-complete class="mfg-primary" ${!p.possible?'disabled':''}>Complete production</button></div>`);$('mfgDialogBody').querySelector('[data-plan-close]').onclick=()=>{$('mfgDialog').close();produceForm();};const button=$('mfgDialogBody').querySelector('[data-plan-complete]');button.onclick=async()=>{if(started!==scope()){ $('mfgDialogBody').querySelector('.mfg-error').textContent='Workspace selection changed. Preview again.';return;}button.disabled=true;try{await mutate('/production/complete',{...body,preview_hash:p.preview_hash});$('mfgDialog').close();selected='production';location.hash=selected;await load();}catch(e){$('mfgDialogBody').querySelector('.mfg-error').textContent=e.message;button.disabled=false;}};}
async function action(name,record){try{if(name==='batch-search'){const q=$('mfgBatchQuery').value.trim();if(!q){batchSearch=null;render();return;}const started=scope(),result=await api('/batches/search?query='+encodeURIComponent(q));if(started!==scope())return;batchSearch={query:q,...result};render();return;}if(name==='batch-clear'){batchSearch=null;render();return;}if(name==='material')return materialForm();if(name==='receive')return receiveForm(record);if(name==='product')return productForm();if(name==='recipe')return recipeForm(record);if(name==='produce')return produceForm();if(name==='equipment')return equipmentForm(record);if(name==='timer'||name==='timer-ready')return timerForm(name==='timer-ready'?'ready':'other');if(name==='adjust')return adjustForm(record);if(name.startsWith('status-'))return statusForm(name.slice(7),record);if(name.startsWith('trace-'))return trace(name.slice(6),record);if(name==='equipment-history')return history(record);if(name.startsWith('equipment-'))return equipmentAction(name.slice(10),record);if(name.startsWith('archive-')){const type={material:'materials',equipment:'equipment',recipe:'recipes'}[name.slice(8)],r=data[type].find(x=>x.id===record);if(!window.confirm((r.archived?'Restore ':'Archive ')+r.name+'? Saved history will remain.'))return;await mutate('/archive/'+type+'/'+record,{archived:!r.archived},'PATCH');await load();}if(name.startsWith('timer-')){const t=data.timers.find(x=>x.id===record),a=name.slice(6);if(!window.confirm((a==='cancelled'?'Cancel ':'Acknowledge ')+t.title+'? This does not change stock or equipment usage.'))return;await mutate('/timers/'+record+'/action',{action:a});await load();window.InventoryManufacturing?.refresh();}}catch(e){notice(e.message,true);}}
async function start(){if(!InventoryAPI.requireLogin())return;try{await window.InventoryTheme?.loadFromAccount();await InventoryTopbar.init('inventory-topbar');await window.InventoryWorkspace?.init();}catch(e){console.warn('Manufacturing selectors:',e.message);}await load();$('mfgCloseDialog').onclick=()=>$('mfgDialog').close();document.addEventListener('click',e=>{const tab=e.target.closest('[data-tab]');if(tab){selected=tab.dataset.tab;location.hash=selected;render();return;}const a=e.target.closest('[data-action]');if(a&&!a.disabled)action(a.dataset.action,a.dataset.id);});window.addEventListener('hashchange',()=>{selected=location.hash.slice(1)||'overview';if(data.recipes)render();});window.addEventListener('inventory-selection-changed',()=>{$('mfgDialog').close();batchSearch=null;load();});document.addEventListener('visibilitychange',()=>{if(!document.hidden)load();});interval=setInterval(()=>{countdowns();},1000);setInterval(()=>{if(!document.hidden&&!loading&&scope()===loadedScope&&data.status?.allowed)load();},60000);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
