(function(){
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const scope=()=>localStorage.getItem('inventoryos_selected_workspace_id')+'|'+InventoryAPI.getSelectedInventoryHeader();
let data={},draft=[],draftScope='',preview=null,busy=false;
const write=()=>data.status?.enabled&&data.status?.allowed&&data.status?.role!=='viewer';
function row(value={}){return '<div class="mfg-calculator-row" data-calculator-row><label>Recipe<select name="recipe_id" required><option value="">Choose recipe…</option>'+data.recipes.filter(r=>!r.archived).map(r=>'<option value="'+esc(r.id)+'" '+(r.id===value.recipe_id?'selected':'')+'>'+esc(r.name)+'</option>').join('')+'</select></label><label>Finished items<input name="qty" type="number" min="1" max="1000000" step="1" required value="'+esc(value.qty||1)+'"></label><button type="button" data-calculator-remove>Remove</button></div>';}
function collect(){return [...document.querySelectorAll('[data-calculator-row]')].map(r=>({recipe_id:r.querySelector('[name=recipe_id]').value,qty:r.querySelector('[name=qty]').value}));}
function remember(){draft=collect();preview=null;try{localStorage.setItem('inventoryos_recipe_draft:'+scope(),JSON.stringify(draft));}catch{}const result=document.getElementById('recipeCalculatorResult');if(result)result.innerHTML='';}
function result(plan){return '<div class="mfg-notice"><strong>'+plan.recipes.map(r=>esc(r.qty+' × '+r.name)).join(' + ')+'</strong><p>Shared ingredients are combined below. Available stock excludes held, recalled and expired batches. Your saved pending material plans are included once.</p></div><div class="mfg-table-wrap"><table class="mfg-table"><thead><tr><th>Material</th><th>This calculation</th><th>Earlier pending plans</th><th>Total needed</th><th>Available</th><th>Combined order</th></tr></thead><tbody>'+plan.materials.map(m=>'<tr><td>'+esc(m.name)+'</td><td>'+esc(m.required_display+' '+m.unit)+'</td><td>'+esc(m.pending_display+' '+m.unit)+'</td><td>'+esc(m.combined_display+' '+m.unit)+'</td><td>'+esc(m.available_display+' '+m.unit)+'</td><td><strong>'+esc(m.order_display+' '+m.unit)+'</strong></td></tr>').join('')+'</tbody></table></div><details class="mfg-notice"><summary>See quantities for each recipe</summary>'+plan.recipes.map(r=>'<h3>'+esc(r.qty+' × '+r.name)+'</h3><ul>'+r.components.map(c=>'<li>'+esc(c.name+': '+c.required+' '+c.unit+' ('+c.per_item+' per item)')+'</li>').join('')+'</ul>').join('')+'</details><div class="mfg-actions"><button type="button" class="mfg-primary" id="queueRecipeMaterials" '+(!write()?'disabled':'')+'>Add combined plan to Reordering</button><a href="reorders.html">View Reordering</a></div><p class="mfg-muted">Saving combines only pending, unplaced material plans. Placed orders keep their agreed quantities. These plans do not reserve stock or complete production. Clear pending material plans in Reordering when they are no longer needed.</p>';
}
function view(d){data=d;if(draftScope!==scope()){draftScope=scope();preview=null;try{draft=JSON.parse(localStorage.getItem('inventoryos_recipe_draft:'+draftScope)||'[]');}catch{draft=[];}}if(!Array.isArray(draft)||!draft.length)draft=[{}];return '<div class="mfg-toolbar"><div><h2>Calculate recipe materials</h2><p class="mfg-muted">Plan several recipes together and see one combined ingredient list.</p></div><a href="reorders.html">Open Reordering</a></div>'+(!data.recipes.some(r=>!r.archived)?'<div class="mfg-empty">Create a recipe first, then return here to calculate quantities.</div>':'<form id="recipeCalculatorForm" class="mfg-form"><div id="recipeCalculatorRows">'+draft.map(row).join('')+'</div><div class="mfg-actions"><button type="button" id="addCalculatorRecipe">Add another recipe</button><button type="submit" class="mfg-primary">Calculate requirements</button></div></form><div id="recipeCalculatorMessage" class="mfg-error" role="status"></div><div id="recipeCalculatorResult">'+(preview&&preview.scope===scope()?result(preview.plan):'')+'</div>');}
document.addEventListener('input',e=>{if(e.target.closest('#recipeCalculatorForm'))remember();});
document.addEventListener('click',async e=>{if(e.target.closest('#addCalculatorRecipe')){document.getElementById('recipeCalculatorRows').insertAdjacentHTML('beforeend',row());remember();}if(e.target.closest('[data-calculator-remove]')){e.target.closest('[data-calculator-row]').remove();remember();}const button=e.target.closest('#queueRecipeMaterials');if(!button||button.disabled||!preview||busy)return;const p=preview;if(p.scope!==scope())return;busy=true;button.disabled=true;const message=document.getElementById('recipeCalculatorMessage');try{const identity=p.scope+'|'+JSON.stringify(p.body),key='inventoryos_recipe_order_pending';let old;try{old=JSON.parse(localStorage.getItem(key)||'null');}catch{}const request_id=old?.identity===identity?old.request_id:crypto.randomUUID();localStorage.setItem(key,JSON.stringify({identity,request_id}));const response=await InventoryAPI.request('/manufacturing/calculate/orders',{method:'POST',body:JSON.stringify({...p.body,preview_hash:p.plan.preview_hash,request_id})});if(!response.success)throw Error(response.error||'Could not save recipe material plan');localStorage.removeItem(key);preview=null;document.getElementById('recipeCalculatorResult').innerHTML='<div class="mfg-notice">Saved. Shared materials are combined with earlier pending plans. <a href="reorders.html">Open Reordering to review or mark them ordered.</a><p>Email summaries follow your saved Email reminder preferences. New recipe schedules default to 5pm UK time.</p></div>';message.textContent='';}catch(error){message.textContent=error.message;button.disabled=false;}finally{busy=false;}});
document.addEventListener('submit',async e=>{if(e.target.id!=='recipeCalculatorForm')return;e.preventDefault();if(busy)return;const started=scope(),recipes=collect(),button=e.target.querySelector('[type=submit]'),message=document.getElementById('recipeCalculatorMessage');if(!recipes.length){message.textContent='Add at least one recipe.';return;}busy=true;button.disabled=true;message.textContent='Calculating…';try{const body={recipes},r=await InventoryAPI.request('/manufacturing/calculate',{method:'POST',body:JSON.stringify(body)});if(started!==scope())return;if(!r.success)throw Error(r.error||'Could not calculate materials');draft=recipes;preview={scope:started,body,plan:r.plan};document.getElementById('recipeCalculatorResult').innerHTML=result(r.plan);message.textContent='';}catch(error){message.textContent=error.message;}finally{busy=false;button.disabled=false;}});
window.InventoryRecipeCalculator={view};
})();
